[project]
title = "Iris Analysis"
version = "0.1.0"
port = 8501

[branding]
name = "Iris Analysis"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#aa1f7b"

[data.postgres]
host = "localhost"            # PostgreSQL host
port = 5432                   # PostgreSQL port
dbname = "mydb"              # Database name
user = "user"                # Username
# password is stored in secrets.toml
