[project]
title = "Earthquake Report"
version = "0.1.0"
port = 8501

[branding]
name = "Earthquake Report"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#964B00"

[data.postgres]
host = "localhost"            # PostgreSQL host
port = 5432                   # PostgreSQL port
dbname = "mydb"              # Database name
user = "user"                # Username
# password is stored in secrets.toml
